package com.lfgj.product.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.lfgj.product.model.Product;

/**
 * Generated by Blade.
 * 2017-09-09 11:53:09
 */
public interface ProductService extends IService<Product>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);
	
	public boolean saveProduct(Product product);
	
	public boolean saveAdjust(Product product);
	
	public void initDateAdjust();

}
