package com.rrgy.sms.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.sms.model.SmsConfig;

/**
 * Generated by Blade.
 * 2017-01-04 16:31:00
 */
public interface SmsConfigService extends IService<SmsConfig>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
