package com.rrgy.sms.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.sms.model.Sms;

/**
 * Generated by Blade.
 * 2017-01-04 16:31:00
 */
public interface SmsService extends IService<Sms>{
	/**
	 * 验证短信验证码
	 * @param mobile
	 * @param code
	 * @return
	 */
	public boolean findValidSms(Object mobile,Object code);

	/**
	 * 更新短信验证码状态
	 * @param mobile
	 */
	public void updateSms(String mobile);
	
	/**
	 * 发送短信验证码
	 * @param mobile
	 * @return
	 */
	public Map<String, Object> sendCode(String mobile)throws Exception;
}
