package com.rrgy.benefit.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.rrgy.benefit.model.Benefit;
import com.rrgy.benefit.service.BenefitService;

/**
 * Generated by Blade.
 * 2017-01-04 12:43:23
 */
@Controller
@RequestMapping("/benefit")
public class BenefitController extends BaseController {
	private static String CODE = "benefit";
	private static String PREFIX = "dt_youhuizubie";
	private static String LIST_SOURCE = "benefit.list";
	private static String BASE_PATH = "/benefit/";
	
	@Autowired
	BenefitService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "benefit.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "benefit_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		Benefit benefit = service.findById(id);
		mm.put("model", JsonKit.toJson(benefit));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "benefit_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		Benefit benefit = service.findById(id);
		mm.put("model", JsonKit.toJson(benefit));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "benefit_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Benefit benefit = mapping(PREFIX, Benefit.class);
		boolean temp = service.save(benefit);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Benefit benefit = mapping(PREFIX, Benefit.class);
		boolean temp = service.update(benefit);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
