package com.lfgj.financial.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.lfgj.financial.model.Financial;

/**
 * Generated by Blade.
 * 2017-09-18 21:29:22
 */
public interface FinancialService extends IService<Financial>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
