package com.lfgj.financial.service;

import com.lfgj.financial.model.Financial;
import com.rrgy.core.base.service.IService;

/**
 * Generated by Blade.
 * 2017-09-18 21:29:22
 */
public interface PayInfoService extends IService<Financial>{
	
	/**
	 * 同步状态
	 * @param id
	 * @return
	 */
	boolean syncStatus(String id);
	
	public boolean editStatus(Integer person_id);
	
	public boolean refalsePay();
}
