package com.lfgj.order.model;

import java.util.Date;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;

import com.lfgj.util.LfConstant;
import com.rrgy.core.base.model.BaseModel;
import com.rrgy.core.toolbox.kit.MathKit;

/**
 * Generated by Blade.
 * 2017-09-19 21:51:02
 */
@Table(name = "dt_orders")
@SuppressWarnings("serial")
public class Order extends BaseModel {

	private Integer id;
	private Integer buy_count; //数量
	private Integer buy_type; //购买类型
	private Integer person_id; //会员ＩＤ
	private Integer product_id; //产品ＩＤ
	private Integer productsale_id;
	private Integer status; //状态
	private String buy_price; //买价
	private BigDecimal earn; //盈亏
	private BigDecimal fee; //手续费
	private BigDecimal order_money; //订单金额
	private BigDecimal person_money; //余额
	private BigDecimal per_price; //每手价格
	private BigDecimal total_price; //总金额（含 手续费）
	private String person_name; //姓名
	private String person_phone; //手机号
	private String person_tuijian; //推荐人
	private String product_name; //产品名称
	private String code; //产品编码
	private String code_name; //产品交易编码
	private String sale_price; //卖价
	private Date buy_time; //建仓时间
	private Date sale_time; //平仓时间
	private String order_num;
	private Integer is_agent;
	private BigDecimal up_earn;//止盈
	private BigDecimal low_earn;//止损
	
	private String up_earn_name;//止盈
	private String low_earn_name;//止损
	
	private BigDecimal order_earn;
	private BigDecimal yinkui; //浮动盈亏
	private BigDecimal min_point;
	
	private String up_price; //盈卖价
	private String low_price; //亏卖价
	
	private String status_name;
	private String buy_type_name;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getBuy_count() {
		return buy_count;
	}
	
	public void setBuy_count(Integer buy_count) {
		this.buy_count = buy_count;
	}
	
	public Integer getBuy_type() {
		return buy_type;
	}
	
	public void setBuy_type(Integer buy_type) {
		this.buy_type = buy_type;
	}
	
	public Integer getPerson_id() {
		return person_id;
	}
	
	public void setPerson_id(Integer person_id) {
		this.person_id = person_id;
	}
	
	public Integer getProduct_id() {
		return product_id;
	}
	
	public void setProduct_id(Integer product_id) {
		this.product_id = product_id;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public String getBuy_price() {
		return buy_price;
	}
	
	public void setBuy_price(String buy_price) {
		this.buy_price = buy_price;
	}
	
	public BigDecimal getEarn() {
		return earn;
	}
	
	public void setEarn(BigDecimal earn) {
		this.earn = earn;
	}
	
	public BigDecimal getFee() {
		return fee;
	}
	
	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}
	
	public BigDecimal getOrder_money() {
		return order_money;
	}
	
	public void setOrder_money(BigDecimal order_money) {
		this.order_money = order_money;
	}
	
	public BigDecimal getPerson_money() {
		return person_money;
	}
	
	public void setPerson_money(BigDecimal person_money) {
		this.person_money = person_money;
	}
	
	public String getPerson_name() {
		return person_name;
	}
	
	public void setPerson_name(String person_name) {
		this.person_name = person_name;
	}
	
	public String getPerson_phone() {
		return person_phone;
	}
	
	public void setPerson_phone(String person_phone) {
		this.person_phone = person_phone;
	}
	
	public String getPerson_tuijian() {
		return person_tuijian;
	}
	
	public void setPerson_tuijian(String person_tuijian) {
		this.person_tuijian = person_tuijian;
	}
	
	public String getProduct_name() {
		return product_name;
	}
	
	public void setProduct_name(String product_name) {
		this.product_name = product_name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getSale_price() {
		return sale_price;
	}
	
	public void setSale_price(String sale_price) {
		this.sale_price = sale_price;
	}
	
	public Date getBuy_time() {
		return buy_time;
	}
	
	public void setBuy_time(Date buy_time) {
		this.buy_time = buy_time;
	}
	
	public Date getSale_time() {
		return sale_time;
	}
	
	public void setSale_time(Date sale_time) {
		this.sale_time = sale_time;
	}

	public String getOrder_num() {
		return order_num;
	}

	public void setOrder_num(String order_num) {
		this.order_num = order_num;
	}

	public String getCode_name() {
		return code_name;
	}

	public void setCode_name(String code_name) {
		this.code_name = code_name;
	}

	public BigDecimal getPer_price() {
		return per_price;
	}

	public void setPer_price(BigDecimal per_price) {
		this.per_price = per_price;
	}

	public BigDecimal getTotal_price() {
		return total_price;
	}

	public void setTotal_price(BigDecimal total_price) {
		this.total_price = total_price;
	}

	public Integer getIs_agent() {
		return is_agent;
	}

	public void setIs_agent(Integer is_agent) {
		this.is_agent = is_agent;
	}

	public BigDecimal getUp_earn() {
		return up_earn;
	}

	public void setUp_earn(BigDecimal up_earn) {
		this.up_earn = up_earn;
	}

	public BigDecimal getLow_earn() {
		return low_earn;
	}

	public void setLow_earn(BigDecimal low_earn) {
		this.low_earn = low_earn;
	}	
	
	public Integer getProductsale_id() {
		return productsale_id;
	}

	public void setProductsale_id(Integer productsale_id) {
		this.productsale_id = productsale_id;
	}

	public BigDecimal getOrder_earn() {
		return order_earn;
	}

	public void setOrder_earn(BigDecimal order_earn) {
		this.order_earn = order_earn;
	}

	public BigDecimal getYinkui() {
		return yinkui;
	}

	public void setYinkui(BigDecimal yinkui) {
		this.yinkui = yinkui;
	}

	public String getUp_price() {
		return up_price;
	}

	public void setUp_price(String up_price) {
		this.up_price = up_price;
	}

	public String getLow_price() {
		return low_price;
	}

	public void setLow_price(String low_price) {
		this.low_price = low_price;
	}

	public BigDecimal getMin_point() {
		return min_point;
	}

	public void setMin_point(BigDecimal min_point) {
		this.min_point = min_point;
	}

	public String getStatus_name() {
		return LfConstant.ORDER_STATUS_TYPE.get(status+"");
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getBuy_type_name() {
		return LfConstant.ORDER_BUY_TYPE.get(buy_type+"");
	}

	public void setBuy_type_name(String buy_type_name) {
		this.buy_type_name = buy_type_name;
	}

	public String getUp_earn_name() {
		BigDecimal uearn = up_earn.multiply(BigDecimal.valueOf(100));
		return MathKit.clearZero(uearn)+"%";
	}

	public void setUp_earn_name(String up_earn_name) {
		this.up_earn_name = up_earn_name;
	}

	public String getLow_earn_name() {
		BigDecimal learn = low_earn.multiply(BigDecimal.valueOf(100));
		return MathKit.clearZero(learn)+"%";
	}

	public void setLow_earn_name(String low_earn_name) {
		this.low_earn_name = low_earn_name;
	}

}
