package com.rrgy.exchange.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.exchange.model.ExchangeGoods;

/**
 * Generated by Blade.
 * 2017-03-09 13:54:49
 */
public interface ExchangeGoodsService extends IService<ExchangeGoods>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
