package com.rrgy.person.service;

import java.util.Map;

import com.rrgy.common.vo.ShiroUser;
import com.rrgy.core.base.service.IService;
import com.rrgy.person.model.Person;
import com.lfgj.tixian.model.Tixianjilu;

/**
 * Generated by Blade.
 * 2016-12-29 12:54:00
 */
public interface PersonService extends IService<Person>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

	/**
	 * 审核
	 * @param u
	 * @param ids
	 * @return
	 */
	public int auditPerson(ShiroUser u, String ids);

	/**
	 * 三级审核
	 * @param u
	 * @param person
	 * @return
	 */
	public int auditLevelPerson(ShiroUser u, Person person)throws Exception;
	
	/**
	 * 回购
	 * @param tixian
	 * @return
	 */
	public boolean savebuydou(Tixianjilu tixian);

	/**
	 * 修改，验证手机号码是否已存在
	 * @param person
	 * @return
	 * @throws Exception
	 */
	boolean checkMobile(Person person);

}
