package com.lfgj.tixian.model;

import java.util.Date;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import org.jeecgframework.poi.excel.annotation.Excel;

import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-01-09 15:38:45
 */
@Table(name = "dt_tixianjilu")
@SuppressWarnings("serial")
public class Tixianjilu extends BaseModel {

	private Integer id;
	private Integer fangshi;
	@Excel(name="状态",orderNum="11",replace={"申请中_1","已打款_2","退回_3"})
	private Integer status; //状态 1申请2打款3退回
	@Excel(name="会员ID号",orderNum="2")
	private Integer userId; //用户id
	private Integer yinhangka; //银行卡
	@Excel(name="提现金额",orderNum="9")
	private BigDecimal amount; //金额
	private BigDecimal shouxufei; //手续费
	private BigDecimal shui; //税
	@Excel(name="订单号",orderNum="1")
	private String tixianNum;//订单号
	@Excel(name="退回原因",orderNum="14")
	private String yuanyin; //退回原因
	@Excel(name="操作时间",orderNum="12",exportFormat="yyyy-MM-dd HH:mm:ss")
	private Date add_time; //操作时间
	@Excel(name="打款时间",orderNum="13",exportFormat="yyyy-MM-dd HH:mm:ss")
	private Date dakuan_time; //打款时间
	private String kahumobile;
	@Excel(name="开户行",orderNum="3")
	private String kaihuhang;//开户行
	@Excel(name="开户名",orderNum="4")
	private String kaihuming;//开户名
	@Excel(name="卡号",orderNum="5")
	private String kahao;//卡号
	@Excel(name="省",orderNum="6")
	private String sheng;
	@Excel(name="市",orderNum="7")
	private String shi;
	@Excel(name="支行",orderNum="8")
	private String zhihang;
	@Excel(name="交易号",orderNum="10")
	private String trade_no;
	
	private Integer file_id;
	private String file_path;
	
	/*扩展属性*/
	private String shijiamount;//实际金额
	private String real_name;//用户名
	private String status_name;//状态
	@Excel(name="身份证",orderNum="2")
	private String idcart;//身份
	private String xiangxindizhi;//详细地址
	private String user_name;//用户名
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getFangshi() {
		return fangshi;
	}
	
	public void setFangshi(Integer fangshi) {
		this.fangshi = fangshi;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public Integer getUserId() {
		return userId;
	}
	
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	public Integer getYinhangka() {
		return yinhangka;
	}
	
	public void setYinhangka(Integer yinhangka) {
		this.yinhangka = yinhangka;
	}
	
	public BigDecimal getAmount() {
		return amount;
	}
	
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	public BigDecimal getShouxufei() {
		return shouxufei;
	}
	
	public void setShouxufei(BigDecimal shouxufei) {
		this.shouxufei = shouxufei;
	}
	
	public BigDecimal getShui() {
		return shui;
	}
	
	public void setShui(BigDecimal shui) {
		this.shui = shui;
	}
	
	public String getTixianNum() {
		return tixianNum;
	}
	
	public void setTixianNum(String tixianNum) {
		this.tixianNum = tixianNum;
	}
	
	public String getYuanyin() {
		return yuanyin;
	}
	
	public void setYuanyin(String yuanyin) {
		this.yuanyin = yuanyin;
	}
	
	public Date getAdd_time() {
		return add_time;
	}
	
	public void setAdd_time(Date add_time) {
		this.add_time = add_time;
	}
	
	public Date getDakuan_time() {
		return dakuan_time;
	}
	
	public void setDakuan_time(Date dakuan_time) {
		this.dakuan_time = dakuan_time;
	}

	public String getShijiamount() {
		return shijiamount;
	}

	public void setShijiamount(String shijiamount) {
		this.shijiamount = shijiamount;
	}

	public String getStatus_name() {
		return status_name;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getKaihuhang() {
		return kaihuhang;
	}

	public void setKaihuhang(String kaihuhang) {
		this.kaihuhang = kaihuhang;
	}

	public String getKaihuming() {
		return kaihuming;
	}

	public void setKaihuming(String kaihuming) {
		this.kaihuming = kaihuming;
	}

	public String getKahao() {
		return kahao;
	}

	public void setKahao(String kahao) {
		this.kahao = kahao;
	}

	public String getXiangxindizhi() {
		return xiangxindizhi;
	}

	public void setXiangxindizhi(String xiangxindizhi) {
		this.xiangxindizhi = xiangxindizhi;
	}

	public Integer getFile_id() {
		return file_id;
	}

	public void setFile_id(Integer file_id) {
		this.file_id = file_id;
	}

	public String getFile_path() {
		return file_path;
	}

	public void setFile_path(String file_path) {
		this.file_path = file_path;
	}

	public String getKahumobile() {
		return kahumobile;
	}

	public void setKahumobile(String kahumobile) {
		this.kahumobile = kahumobile;
	}

	public String getReal_name() {
		return real_name;
	}

	public void setReal_name(String real_name) {
		this.real_name = real_name;
	}

	public String getIdcart() {
		return idcart;
	}

	public void setIdcart(String idcart) {
		this.idcart = idcart;
	}

	
	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public String getSheng() {
		return sheng;
	}

	public void setSheng(String sheng) {
		this.sheng = sheng;
	}

	public String getShi() {
		return shi;
	}

	public void setShi(String shi) {
		this.shi = shi;
	}

	public String getZhihang() {
		return zhihang;
	}

	public void setZhihang(String zhihang) {
		this.zhihang = zhihang;
	}

	public String getTrade_no() {
		return trade_no;
	}

	public void setTrade_no(String trade_no) {
		this.trade_no = trade_no;
	}

}
