package com.lfgj.system.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-04 21:47:01
 */
@Table(name = "dt_top")
@SuppressWarnings("serial")
public class Top extends BaseModel {

	private Integer id; //自增ID
	private Integer is_cash; //保证金
	private Integer is_stop; //是否休盘
	private Integer last_update_user;
	private String top; //龙虎榜
	private Date create_time;
	private Date last_update_time;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getIs_cash() {
		return is_cash;
	}
	
	public void setIs_cash(Integer is_cash) {
		this.is_cash = is_cash;
	}
	
	public Integer getIs_stop() {
		return is_stop;
	}
	
	public void setIs_stop(Integer is_stop) {
		this.is_stop = is_stop;
	}
	
	public Integer getLast_update_user() {
		return last_update_user;
	}
	
	public void setLast_update_user(Integer last_update_user) {
		this.last_update_user = last_update_user;
	}
	
	public String getTop() {
		return top;
	}
	
	public void setTop(String top) {
		this.top = top;
	}
	
	public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	
	public Date getLast_update_time() {
		return last_update_time;
	}
	
	public void setLast_update_time(Date last_update_time) {
		this.last_update_time = last_update_time;
	}
	

}
