package com.lfgj.yongjin.service;


import com.rrgy.core.base.service.IService;

import java.util.Map;

import com.lfgj.tixian.model.Tixianjilu;

/**
 * Generated by Blade.
 * 2017-01-09 15:38:45
 */
public interface YongjinService extends IService<Tixianjilu>{
	
	public String querySum(Map<String,Object> params);

}
