package com.lfgj.online.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-15 16:10:50
 */
@Table(name = "dt_online_service")
@SuppressWarnings("serial")
public class OnlineService extends BaseModel {

	private Integer id;
	private Integer replay_id; //回复人ID
	private Integer send_id; //发送人
	private Integer status; //状态,0:待回复，１：已回复
	private String msg; //消息
	private String replay; //回复内容
	private Date create_time; //创建时间
	private Date replay_time; //回复时间
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getReplay_id() {
		return replay_id;
	}
	
	public void setReplay_id(Integer replay_id) {
		this.replay_id = replay_id;
	}
	
	public Integer getSend_id() {
		return send_id;
	}
	
	public void setSend_id(Integer send_id) {
		this.send_id = send_id;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public String getMsg() {
		return msg;
	}
	
	public void setMsg(String msg) {
		this.msg = msg;
	}
	
	public String getReplay() {
		return replay;
	}
	
	public void setReplay(String replay) {
		this.replay = replay;
	}
	
	public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	
	public Date getReplay_time() {
		return replay_time;
	}
	
	public void setReplay_time(Date replay_time) {
		this.replay_time = replay_time;
	}
	

}
