package com.lfgj.product.model;

import java.util.Date;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-09 11:53:17
 */
@Table(name = "dt_product_sale")
@SuppressWarnings("serial")
public class ProductSale extends BaseModel {

	private Integer id;
	private BigDecimal adjust; //动态调整
	private Integer creator; //创建人
	private BigDecimal diancs; //点乘数
	private Integer product_id; //商品ID
	private Integer sort; //排序
	private BigDecimal yinkui; //浮动盈亏
	private String code_name; //代码名称
	private String code; //代码名称
	private BigDecimal fee; //手续费
	private BigDecimal price; //价格
	private Date create_time; //创建时间
	
	private String product_name; //代码名称
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public BigDecimal getAdjust() {
		return adjust;
	}
	
	public void setAdjust(BigDecimal adjust) {
		this.adjust = adjust;
	}
	
	public Integer getCreator() {
		return creator;
	}
	
	public void setCreator(Integer creator) {
		this.creator = creator;
	}
	
	public BigDecimal getDiancs() {
		return diancs;
	}
	
	public void setDiancs(BigDecimal diancs) {
		this.diancs = diancs;
	}
	
	public Integer getProduct_id() {
		return product_id;
	}
	
	public void setProduct_id(Integer product_id) {
		this.product_id = product_id;
	}
	
	public Integer getSort() {
		return sort;
	}
	
	public void setSort(Integer sort) {
		this.sort = sort;
	}
	
	public BigDecimal getYinkui() {
		return yinkui;
	}
	
	public void setYinkui(BigDecimal yinkui) {
		this.yinkui = yinkui;
	}
	
	public String getCode_name() {
		return code_name;
	}
	
	public void setCode_name(String code_name) {
		this.code_name = code_name;
	}
	
	public BigDecimal getFee() {
		return fee;
	}
	
	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}
	
	public BigDecimal getPrice() {
		return price;
	}
	
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getProduct_name() {
		return product_name;
	}

	public void setProduct_name(String product_name) {
		this.product_name = product_name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	

}
