package com.rrgy.exchange.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade. 2017-03-08 11:46:41
 */
@Table(name = "exchange_order_address")
@SuppressWarnings("serial")
public class ExchangeOrderAddress extends BaseModel {

	private Integer id; // 主键id
	private Integer order_id; // 订单id
	private Integer order_user_id; // 订单用户id
	private String address; // 地址
	private String city; // 市
	private String consignee; // 收货人
	private String order_number; // 订单编号
	private String order_user_name; // 订单用户名称
	private String phone; // 联系电话
	private String postcode; // 邮编
	private String province; // 省
	private String area;// 区
	private String province_name; // 省
	private String city_name; // 市
	private String area_name;// 区
	private Date create_time; // 添加时间

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Integer order_id) {
		this.order_id = order_id;
	}

	public Integer getOrder_user_id() {
		return order_user_id;
	}

	public void setOrder_user_id(Integer order_user_id) {
		this.order_user_id = order_user_id;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getConsignee() {
		return consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public String getOrder_number() {
		return order_number;
	}

	public void setOrder_number(String order_number) {
		this.order_number = order_number;
	}

	public String getOrder_user_name() {
		return order_user_name;
	}

	public void setOrder_user_name(String order_user_name) {
		this.order_user_name = order_user_name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getProvince_name() {
		return province_name;
	}

	public void setProvince_name(String province_name) {
		this.province_name = province_name;
	}

	public String getCity_name() {
		return city_name;
	}

	public void setCity_name(String city_name) {
		this.city_name = city_name;
	}

	public String getArea_name() {
		return area_name;
	}

	public void setArea_name(String area_name) {
		this.area_name = area_name;
	}

}
