package com.rrgy.exchange.model;

import java.util.Date;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade. 2017-03-08 11:45:50
 */
@Table(name = "exchange_order_detail")
@SuppressWarnings("serial")
public class ExchangeOrderDetail extends BaseModel {

	private Integer id;
	private Integer order_id;// 订单id
	private Integer goods_id; // 商品id
	private Integer order_user_id; // 用户id
	private Long exchange_count; // 兑换数量
	private BigDecimal exchange_credits; // 兑换积分
	private BigDecimal exchange_total_credits; // 兑换总积分
	private String goods_details; // 商品详情
	private String goods_img1; // 商品图片1
	private String goods_img2; // 商品图片2
	private String goods_img3; // 商品图片3
	private String goods_img4; // 商品图片4
	private String goods_img5; // 商品图片5
	private String goods_name; // 商品名称
	private String goods_number; // 商品编码
	private String order_number; // 订单编号
	private String order_user_name; // 用户名
	private Date create_time; // 添加日期

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Integer order_id) {
		this.order_id = order_id;
	}

	public Integer getGoods_id() {
		return goods_id;
	}

	public void setGoods_id(Integer goods_id) {
		this.goods_id = goods_id;
	}

	public Integer getOrder_user_id() {
		return order_user_id;
	}

	public void setOrder_user_id(Integer order_user_id) {
		this.order_user_id = order_user_id;
	}

	public Long getExchange_count() {
		return exchange_count;
	}

	public void setExchange_count(Long exchange_count) {
		this.exchange_count = exchange_count;
	}

	public BigDecimal getExchange_credits() {
		return exchange_credits;
	}

	public void setExchange_credits(BigDecimal exchange_credits) {
		this.exchange_credits = exchange_credits;
	}

	public BigDecimal getExchange_total_credits() {
		return exchange_total_credits;
	}

	public void setExchange_total_credits(BigDecimal exchange_total_credits) {
		this.exchange_total_credits = exchange_total_credits;
	}

	public String getGoods_details() {
		return goods_details;
	}

	public void setGoods_details(String goods_details) {
		this.goods_details = goods_details;
	}

	public String getGoods_img1() {
		return goods_img1;
	}

	public void setGoods_img1(String goods_img1) {
		this.goods_img1 = goods_img1;
	}

	public String getGoods_img2() {
		return goods_img2;
	}

	public void setGoods_img2(String goods_img2) {
		this.goods_img2 = goods_img2;
	}

	public String getGoods_img3() {
		return goods_img3;
	}

	public void setGoods_img3(String goods_img3) {
		this.goods_img3 = goods_img3;
	}

	public String getGoods_img4() {
		return goods_img4;
	}

	public void setGoods_img4(String goods_img4) {
		this.goods_img4 = goods_img4;
	}

	public String getGoods_img5() {
		return goods_img5;
	}

	public void setGoods_img5(String goods_img5) {
		this.goods_img5 = goods_img5;
	}

	public String getGoods_name() {
		return goods_name;
	}

	public void setGoods_name(String goods_name) {
		this.goods_name = goods_name;
	}

	public String getGoods_number() {
		return goods_number;
	}

	public void setGoods_number(String goods_number) {
		this.goods_number = goods_number;
	}

	public String getOrder_number() {
		return order_number;
	}

	public void setOrder_number(String order_number) {
		this.order_number = order_number;
	}

	public String getOrder_user_name() {
		return order_user_name;
	}

	public void setOrder_user_name(String order_user_name) {
		this.order_user_name = order_user_name;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

}
