package com.lfgj.article.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-03 11:17:21
 */
@Table(name = "dt_article")
@SuppressWarnings("serial")
public class Article extends BaseModel {

	private Integer id; //自增ID
	private Integer category_id; //类别ID
	private Integer channel_id; //频道ID
	private Integer click; //浏览次数
	private Integer is_hot; //是否热门
	private Integer is_msg; //是否允许评论
	private Integer is_red; //是否推荐
	private Integer is_slide; //是否幻灯片
	private Integer is_sys; //是否管理员发布0不是1是
	private Integer is_top; //是否置顶
	private Integer sort_id; //排序
	private Integer status; //状态0正常1未审核2锁定
	private Integer vote_id; //关联投票ID
	private Integer wid; //微帐号主键ID
	private String call_index; //调用别名
	private String content; //详细内容
	private String groupids_view; //阅读权限
	private String img_url; //图片地址
	private String link_url; //外部链接
	private String seo_description; //SEO描述
	private String seo_keywords; //SEO关健字
	private String seo_title; //SEO标题
	private String title; //标题
	private String user_name; //用户名
	private String zhaiyao; //内容摘要
	private Date add_time; //创建时间
	private Date update_time; //修改时间
	
	private String category_name; //类别
	private String channel_name; //频道
	private String group_view_name; //范围
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getCategory_id() {
		return category_id;
	}
	
	public void setCategory_id(Integer category_id) {
		this.category_id = category_id;
	}
	
	public Integer getChannel_id() {
		return channel_id;
	}
	
	public void setChannel_id(Integer channel_id) {
		this.channel_id = channel_id;
	}
	
	public Integer getClick() {
		return click;
	}
	
	public void setClick(Integer click) {
		this.click = click;
	}
	
	public Integer getIs_hot() {
		return is_hot;
	}
	
	public void setIs_hot(Integer is_hot) {
		this.is_hot = is_hot;
	}
	
	public Integer getIs_msg() {
		return is_msg;
	}
	
	public void setIs_msg(Integer is_msg) {
		this.is_msg = is_msg;
	}
	
	public Integer getIs_red() {
		return is_red;
	}
	
	public void setIs_red(Integer is_red) {
		this.is_red = is_red;
	}
	
	public Integer getIs_slide() {
		return is_slide;
	}
	
	public void setIs_slide(Integer is_slide) {
		this.is_slide = is_slide;
	}
	
	public Integer getIs_sys() {
		return is_sys;
	}
	
	public void setIs_sys(Integer is_sys) {
		this.is_sys = is_sys;
	}
	
	public Integer getIs_top() {
		return is_top;
	}
	
	public void setIs_top(Integer is_top) {
		this.is_top = is_top;
	}
	
	public Integer getSort_id() {
		return sort_id;
	}
	
	public void setSort_id(Integer sort_id) {
		this.sort_id = sort_id;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public Integer getVote_id() {
		return vote_id;
	}
	
	public void setVote_id(Integer vote_id) {
		this.vote_id = vote_id;
	}
	
	public Integer getWid() {
		return wid;
	}
	
	public void setWid(Integer wid) {
		this.wid = wid;
	}
	
	public String getCall_index() {
		return call_index;
	}
	
	public void setCall_index(String call_index) {
		this.call_index = call_index;
	}
	
	public String getContent() {
		return content;
	}
	
	public void setContent(String content) {
		this.content = content;
	}
	
	public String getGroupids_view() {
		return groupids_view;
	}
	
	public void setGroupids_view(String groupids_view) {
		this.groupids_view = groupids_view;
	}
	
	public String getImg_url() {
		return img_url;
	}
	
	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}
	
	public String getLink_url() {
		return link_url;
	}
	
	public void setLink_url(String link_url) {
		this.link_url = link_url;
	}
	
	public String getSeo_description() {
		return seo_description;
	}
	
	public void setSeo_description(String seo_description) {
		this.seo_description = seo_description;
	}
	
	public String getSeo_keywords() {
		return seo_keywords;
	}
	
	public void setSeo_keywords(String seo_keywords) {
		this.seo_keywords = seo_keywords;
	}
	
	public String getSeo_title() {
		return seo_title;
	}
	
	public void setSeo_title(String seo_title) {
		this.seo_title = seo_title;
	}
	
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getUser_name() {
		return user_name;
	}
	
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	
	public String getZhaiyao() {
		return zhaiyao;
	}
	
	public void setZhaiyao(String zhaiyao) {
		this.zhaiyao = zhaiyao;
	}
	
	public Date getAdd_time() {
		return add_time;
	}
	
	public void setAdd_time(Date add_time) {
		this.add_time = add_time;
	}
	
	public Date getUpdate_time() {
		return update_time;
	}
	
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public String getCategory_name() {
		return category_name;
	}

	public void setCategory_name(String category_name) {
		this.category_name = category_name;
	}

	public String getChannel_name() {
		return channel_name;
	}

	public void setChannel_name(String channel_name) {
		this.channel_name = channel_name;
	}

	public String getGroup_view_name() {
		return group_view_name;
	}

	public void setGroup_view_name(String group_view_name) {
		this.group_view_name = group_view_name;
	}
	

}
