package com.lfgj.article.model;


import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-02 19:39:14
 */
@Table(name = "dt_article_category")
@SuppressWarnings("serial")
public class Category extends BaseModel {

	private Integer id; //自增ID
	private Integer channel_id; //频道ID
	private Integer class_layer; //类别深度
	private Integer parent_id; //父类别ID
	private Integer sort_id; //排序数字
	private Integer wid; //微帐号主键Id
	private String call_index; //调用别名
	private String class_list; //类别ID列表(逗号分隔开)
	private String content; //备注说明
	private String ico_url; //图标地址
	private String img_url; //图片地址
	private String link_url; //URL跳转地址
	private String seo_description; //SEO描述
	private String seo_keywords; //SEO关健字
	private String seo_title; //SEO标题
	private String title; //类别标题
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getChannel_id() {
		return channel_id;
	}
	
	public void setChannel_id(Integer channel_id) {
		this.channel_id = channel_id;
	}
	
	public Integer getClass_layer() {
		return class_layer;
	}
	
	public void setClass_layer(Integer class_layer) {
		this.class_layer = class_layer;
	}
	
	public Integer getParent_id() {
		return parent_id;
	}
	
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}
	
	public Integer getSort_id() {
		return sort_id;
	}
	
	public void setSort_id(Integer sort_id) {
		this.sort_id = sort_id;
	}
	
	public Integer getWid() {
		return wid;
	}
	
	public void setWid(Integer wid) {
		this.wid = wid;
	}
	
	public String getCall_index() {
		return call_index;
	}
	
	public void setCall_index(String call_index) {
		this.call_index = call_index;
	}
	
	public String getClass_list() {
		return class_list;
	}
	
	public void setClass_list(String class_list) {
		this.class_list = class_list;
	}
	
	public String getContent() {
		return content;
	}
	
	public void setContent(String content) {
		this.content = content;
	}
	
	public String getIco_url() {
		return ico_url;
	}
	
	public void setIco_url(String ico_url) {
		this.ico_url = ico_url;
	}
	
	public String getImg_url() {
		return img_url;
	}
	
	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}
	
	public String getLink_url() {
		return link_url;
	}
	
	public void setLink_url(String link_url) {
		this.link_url = link_url;
	}
	
	public String getSeo_description() {
		return seo_description;
	}
	
	public void setSeo_description(String seo_description) {
		this.seo_description = seo_description;
	}
	
	public String getSeo_keywords() {
		return seo_keywords;
	}
	
	public void setSeo_keywords(String seo_keywords) {
		this.seo_keywords = seo_keywords;
	}
	
	public String getSeo_title() {
		return seo_title;
	}
	
	public void setSeo_title(String seo_title) {
		this.seo_title = seo_title;
	}
	
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	

}
