package com.lfgj.article.model;


import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-02 18:13:22
 */
@Table(name = "dt_channel")
@SuppressWarnings("serial")
public class Channel extends BaseModel {

	private Integer id; //自增ID
	private Integer category_id; //分类ID
	private Integer is_albums; //是否开启相册功能
	private Integer is_attach; //是否开启附件功能
	private Integer is_group_price; //是否开启会员组价格
	private Integer page_size; //每页显示数量
	private Integer sort_id; //排序数字
	private Integer wid; //微帐号主键Id
	private String name; //频道名称
	private String title; //频道标题
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getCategory_id() {
		return category_id;
	}
	
	public void setCategory_id(Integer category_id) {
		this.category_id = category_id;
	}
	
	public Integer getIs_albums() {
		return is_albums;
	}
	
	public void setIs_albums(Integer is_albums) {
		this.is_albums = is_albums;
	}
	
	public Integer getIs_attach() {
		return is_attach;
	}
	
	public void setIs_attach(Integer is_attach) {
		this.is_attach = is_attach;
	}
	
	public Integer getIs_group_price() {
		return is_group_price;
	}
	
	public void setIs_group_price(Integer is_group_price) {
		this.is_group_price = is_group_price;
	}
	
	public Integer getPage_size() {
		return page_size;
	}
	
	public void setPage_size(Integer page_size) {
		this.page_size = page_size;
	}
	
	public Integer getSort_id() {
		return sort_id;
	}
	
	public void setSort_id(Integer sort_id) {
		this.sort_id = sort_id;
	}
	
	public Integer getWid() {
		return wid;
	}
	
	public void setWid(Integer wid) {
		this.wid = wid;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	

}
