package com.rrgy.sms.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.rrgy.sms.model.SmsConfig;
import com.rrgy.sms.service.SmsConfigService;

/**
 * Generated by Blade.
 * 2017-01-04 16:31:00
 */
@Controller
@RequestMapping("/smsConfig")
public class SmsConfigController extends BaseController {
	private static String CODE = "smsConfig";
	private static String PREFIX = "wx_sms_config";
	private static String LIST_SOURCE = "smsConfig.list";
	private static String BASE_PATH = "/smsConfig/";
	
	@Autowired
	SmsConfigService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "smsConfig.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "smsConfig_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		SmsConfig smsConfig = service.findById(id);
		mm.put("model", JsonKit.toJson(smsConfig));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "smsConfig_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		SmsConfig smsConfig = service.findById(id);
		mm.put("model", JsonKit.toJson(smsConfig));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "smsConfig_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		SmsConfig smsConfig = mapping(PREFIX, SmsConfig.class);
		smsConfig.setCreateDate(new Date());
		boolean temp = service.save(smsConfig);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		SmsConfig smsConfig = mapping(PREFIX, SmsConfig.class);
		boolean temp = service.update(smsConfig);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
