package com.lfgj.member.controller;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.lfgj.member.model.Member;
import com.lfgj.member.service.MemberService;
import com.lfgj.util.MD5;
import com.rrgy.common.base.BaseController;
import com.rrgy.common.vo.ShiroUser;
import com.rrgy.core.annotation.Before;
import com.rrgy.core.plugins.dao.Blade;
import com.rrgy.core.shiro.ShiroKit;
import com.rrgy.core.toolbox.Func;
import com.rrgy.core.toolbox.Paras;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.rrgy.core.toolbox.kit.StrKit;
import com.rrgy.system.meta.intercept.AgentIntercept;
import com.rrgy.system.meta.intercept.MemberIntercept;
import com.rrgy.system.meta.intercept.MemberValidator;
import com.rrgy.system.model.User;

/**
 * Generated by Blade.
 * 2017-09-12 16:12:39
 * 会员管理
 */
@Controller
@RequestMapping("/member")
public class MemberController extends BaseController {
	private static String CODE = "member";
	private static String PREFIX = "lf_member";
	private static String LIST_SOURCE = "member.list";
	private static String BASE_PATH = "/member/";
	
	@Autowired
	MemberService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "member.html";
	}
	
	@RequestMapping("/lookupList")
	public String lookupList(ModelMap mm){
		mm.put("code", CODE);
		return BASE_PATH + "member_lookup.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "member_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		Member member = service.findById(id);
		member.setPassword("");
		member.setPay_password("");
		mm.put("model", JsonKit.toJson(member));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "member_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		Member member = service.findById(id);
		
		ShiroUser shiroUser = ShiroKit.getUser();
		User user = Blade.create(User.class).findById(shiroUser.getId());
		if(user.getIs_agent() == 1){
			member.setMobile(StrKit.hidePhone(member.getMobile()));
			member.setBank_mobile(StrKit.hidePhone(member.getBank_mobile()));
			member.setBank_acount("***********");
		}
		
		mm.put("model", JsonKit.toJson(member));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "member_view.html";
	}

	@RequestMapping("/audit")
	public String auditlist(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "member_audit.html";
	}
	
	@ResponseBody
	@RequestMapping("/auditList")
	public Object auditList() {
		MemberIntercept ai = new MemberIntercept();
		ai.status = "2,4";
		Object grid = paginate(LIST_SOURCE, ai);
		return grid;
	}
	
	
	@ResponseBody
	@RequestMapping("/auditOk")
	public AjaxResult auditOk() {
		String ids = getParameter("ids");
		Blade blade = Blade.create(Member.class);
		Paras updateMap = Paras.create().set("status", 0).set("ids", ids.split(","));
		boolean temp = blade.updateBy("status = #{status}", "id in (#{join(ids)})", updateMap);		
		if (temp) {
			return success("审核成功!");
		} else {
			return error("审核失败!");
		}
	}
	
	@ResponseBody
	@RequestMapping("/auditRefuse")
	public AjaxResult auditRefuse() {
		String ids = getParameter("ids");
		Paras updateMap = Paras.create().set("status", 4).set("ids", ids.split(","));
		boolean temp = Blade.create(Member.class).updateBy("status = #{status}", "id in (#{join(ids)})", updateMap);
		if (temp) {
			return success("审核拒绝成功!");
		} else {
			return error("审核拒绝失败!");
		}
	}
	
	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE, new MemberIntercept());
		return grid;
	}
	
	@ResponseBody
	@RequestMapping("/lookuplist")
	public Object lookuplist() {
		MemberIntercept mi = new MemberIntercept();
		mi.is_agent = 1;
		Object grid = paginate(LIST_SOURCE, mi);
		return grid;
	}
	
	@ResponseBody
	@Before(MemberValidator.class)
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		ShiroUser shiroUser = ShiroKit.getUser();
		User loginUser = Blade.create(User.class).findById(shiroUser.getId());
		Member member = mapping(PREFIX, Member.class);
		member.setStatus(0);
		member.setReg_time(new Date());
		member.setAmount(new BigDecimal("0"));
		member.setPoint(new BigDecimal("0"));
		member.setProfi_loss(new BigDecimal("0"));
		member.setRecharge(new BigDecimal("0"));
		member.setWithdraw(new BigDecimal("0"));
		member.setIs_agent(0);
		
//		if(Func.isEmpty(loginUser.getMember_id())){
//			return error("请使用代理商帐号");
//		}
		
		if(Func.isEmpty(member.getParent_id())){
			member.setParent_id(loginUser.getMember_id());
		}

		Member parent = Blade.create(Member.class).findById(member.getParent_id());		
		if(parent.getLevel()!=null&&parent.getLevel()==1){
			member.setParent_ids(parent.getId().toString());
			member.setFirst_parent(parent.getId());
		}else if(!Func.isEmpty(parent.getParent_ids())&&parent.getIs_agent()==1){
			member.setParent_ids(parent.getId()+","+parent.getParent_ids());
			member.setFirst_parent(parent.getFirst_parent());
		}else{
			member.setParent_ids(parent.getParent_ids());
			member.setFirst_parent(parent.getFirst_parent());
		}
		
		member.setParent_name(parent.getReal_name());		
		member.setAgent_id(parent.getAgent_id());
		member.setAgent_name(parent.getAgent_name());

		MD5 md5 = new MD5();
		member.setPassword(md5.enCodeByMD5(member.getMobile(), member.getMobile()));
		member.setPay_password(md5.enCodeByMD5(member.getMobile(), member.getMobile()));
		
		boolean temp = service.save(member);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@Before(MemberValidator.class)
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Member member = mapping(PREFIX, Member.class);
		
		MD5 md5 = new MD5();
		if(StrKit.isNotEmpty(member.getPassword().trim())){
			member.setPassword(md5.enCodeByMD5(member.getPassword(), member.getMobile()));
		}else{
			member.setPassword(null);
		}
		
		if(StrKit.isNotEmpty(member.getPay_password().trim())){
			member.setPay_password(md5.enCodeByMD5(member.getPay_password(), member.getMobile()));
		}else{
			member.setPay_password(null);
		}
		
		boolean temp = service.update(member);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.removeAgent(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
	
	@ResponseBody
	@RequestMapping("/ban")
	public AjaxResult ban() {
		String ids = getParameter("ids");
		Paras updateMap = Paras.create().set("ids", ids.split(","));
		boolean temp = Blade.create(Member.class).updateBy("status = (CASE WHEN STATUS=0 THEN 3 ELSE 0 END)", "id in (#{join(ids)})", updateMap);
		if (temp) {
			return success("操作成功!");
		} else {
			return error("操作失败!");
		}
	}
}
