package com.lfgj.member.model;

import java.util.Date;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-12 16:12:40
 */
@Table(name = "lf_member")
@SuppressWarnings("serial")
public class Member extends BaseModel {

	private Integer id; //自增ID
	private String real_name; //用户姓名
	private Integer login_state; //登录状态
	private Integer parent_id; //推荐人ID
	private String parent_name;
	private Integer status; //用户状态,0正常,1待验证,2待审核,3锁定
	private String bank_acount; //银行卡号
	private String bank_mobile; //银行卡绑定手机号
	private String bank_name; //银行名称
	private String kaihuming; //开户名
	private String idcart; // 身份证号码
	private String city; //城市名称
	private String mobile; //手机号码
	private String parent_ids; //所有上级
	private String password; //登录密码
	private String pay_password; //交易密码
	private BigDecimal point; //用户积分
	private BigDecimal amount; //余额
	private BigDecimal profi_loss; //总盈亏
	private BigDecimal recharge; //总充值
	private BigDecimal withdraw; //总提现
	private Date login_time; //登录时间
	private Date reg_time; //注册时间
	private Integer is_agent; // 是否代理商
	private Integer agent_id; // 所属代理商ID
	private String agent_name; // 所属代理商名称
	private Integer sys_user_id; // 系统账号ID
	private Integer level; // 代理商层级（最高不能超过5级）
	private Integer first_parent;
	private String crypt_id;
	
	private String cashFee;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getLogin_state() {
		return login_state;
	}
	
	public void setLogin_state(Integer login_state) {
		this.login_state = login_state;
	}
	
	public Integer getParent_id() {
		return parent_id;
	}
	
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public BigDecimal getAmount() {
		return amount;
	}
	
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	public String getBank_acount() {
		return bank_acount;
	}
	
	public void setBank_acount(String bank_acount) {
		this.bank_acount = bank_acount;
	}
	
	public String getBank_mobile() {
		return bank_mobile;
	}
	
	public void setBank_mobile(String bank_mobile) {
		this.bank_mobile = bank_mobile;
	}
	
	public String getBank_name() {
		return bank_name;
	}
	
	public void setBank_name(String bank_name) {
		this.bank_name = bank_name;
	}
	
	public String getCity() {
		return city;
	}
	
	public void setCity(String city) {
		this.city = city;
	}
	
	public String getMobile() {
		return mobile;
	}
	
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	public String getParent_ids() {
		return parent_ids;
	}
	
	public void setParent_ids(String parent_ids) {
		this.parent_ids = parent_ids;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getPay_password() {
		return pay_password;
	}
	
	public void setPay_password(String pay_password) {
		this.pay_password = pay_password;
	}
	
	public BigDecimal getPoint() {
		return point;
	}
	
	public void setPoint(BigDecimal point) {
		this.point = point;
	}
	
	public BigDecimal getProfi_loss() {
		return profi_loss;
	}
	
	public void setProfi_loss(BigDecimal profi_loss) {
		this.profi_loss = profi_loss;
	}
	
	public String getReal_name() {
		return real_name;
	}
	
	public void setReal_name(String real_name) {
		this.real_name = real_name;
	}
	
	public BigDecimal getRecharge() {
		return recharge;
	}
	
	public void setRecharge(BigDecimal recharge) {
		this.recharge = recharge;
	}
	
	public BigDecimal getWithdraw() {
		return withdraw;
	}
	
	public void setWithdraw(BigDecimal withdraw) {
		this.withdraw = withdraw;
	}
	
	public Date getLogin_time() {
		return login_time;
	}
	
	public void setLogin_time(Date login_time) {
		this.login_time = login_time;
	}
	
	public Date getReg_time() {
		return reg_time;
	}
	
	public void setReg_time(Date reg_time) {
		this.reg_time = reg_time;
	}

	public String getParent_name() {
		return parent_name;
	}

	public void setParent_name(String parent_name) {
		this.parent_name = parent_name;
	}

	public Integer getIs_agent() {
		return is_agent;
	}

	public void setIs_agent(Integer is_agent) {
		this.is_agent = is_agent;
	}

	public Integer getAgent_id() {
		return agent_id;
	}

	public void setAgent_id(Integer agent_id) {
		this.agent_id = agent_id;
	}

	public String getAgent_name() {
		return agent_name;
	}

	public void setAgent_name(String agent_name) {
		this.agent_name = agent_name;
	}

	public Integer getSys_user_id() {
		return sys_user_id;
	}

	public void setSys_user_id(Integer sys_user_id) {
		this.sys_user_id = sys_user_id;
	}

	public String getCashFee() {
		return cashFee;
	}

	public void setCashFee(String cashFee) {
		this.cashFee = cashFee;
	}

	public String getIdcart() {
		return idcart;
	}

	public void setIdcart(String idcart) {
		this.idcart = idcart;
	}

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getFirst_parent() {
		return first_parent;
	}

	public void setFirst_parent(Integer first_parent) {
		this.first_parent = first_parent;
	}

	public String getKaihuming() {
		return kaihuming;
	}

	public void setKaihuming(String kaihuming) {
		this.kaihuming = kaihuming;
	}

	public String getCrypt_id() {
		return crypt_id;
	}

	public void setCrypt_id(String crypt_id) {
		this.crypt_id = crypt_id;
	}
	
}
