package com.lfgj.system.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.lfgj.system.model.Top;

/**
 * Generated by Blade.
 * 2017-09-04 21:47:01
 */
public interface TopService extends IService<Top>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
