package com.rrgy.payment.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.payment.model.Payment;

/**
 * Generated by Blade.
 * 2017-01-04 13:26:54
 */
public interface PaymentService extends IService<Payment>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
