package com.lfgj.order.service;

import java.util.Map;

import com.lfgj.order.model.Order;
import com.rrgy.core.base.service.IService;

/**
 * Generated by Blade.
 * 2017-09-19 21:51:02
 */
public interface OrderService extends IService<Order>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);
	
	public String saveOrder(String person_id,String psid,String ct,String buytype,String price);
	
	public String updateOrder(String order_id);
	
	public String updateOrder(String order_id,String sale_price,String msg);

}
