package com.lfgj.yongjin.service.impl;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.lfgj.tixian.model.Tixianjilu;
import com.lfgj.yongjin.service.YongjinService;
import com.rrgy.core.base.service.BaseService;
import com.rrgy.core.plugins.dao.Db;
import com.rrgy.core.plugins.dao.Md;
import com.rrgy.core.toolbox.Func;

/**
 * Generated by Blade.
 * 2017-01-09 15:38:45
 */
@Service
public class YongjinServiceImpl extends BaseService<Tixianjilu> implements YongjinService{

	@Override
	public String querySum(Map<String,Object> params){
		String sql = "";
		
		String type = params.get("type").toString();
		
		if("0".equals(type)){ // 总充值
			sql = Md.getSql("yongjin.rechargeTotal");
		}else if("1".equals(type)){ // 总提现
			sql = Md.getSql("yongjin.withdrawTotal");
		}else if("2".equals(type)){ // 总盈亏
			sql = Md.getSql("yongjin.profiLossTotal");
		}else if("3".equals(type)){ // 总手续费
			sql = Md.getSql("yongjin.sxfTotal");
		}else{
			return "0";
		}
		
		String condition = "";
		Object agent_id = params.get("agent_id");
		Object member_id = params.get("member_id");
	    if (!(Func.isEmpty(agent_id))){
	    	condition += " and CASE is_agent WHEN 1 THEN parent_id = " + member_id + " ELSE agent_id = " + agent_id + " END";
	    }else {
//	      params.put("level", "1");
	      condition += " and level = 1";
	    }

	    Object user_id = params.get("user_id_skip");
	    if (!(Func.isEmpty(user_id))) {
	      condition = condition += " and (l.id = '" + user_id + "' or l.real_name like '%" + user_id + "%')";
	    }
	    
	    Object mobile = params.get("mobile");
	    if (!(Func.isEmpty(mobile))) {
	      condition = condition += " and l.mobile = '" + mobile + "'";
	    }
	    
	    sql += " where 1=1 " +condition;
		sql = "select ifnull(sum(total_result),0)amount from ("+sql+")t";
		
		
		String result = Db.queryStr(sql, params); // ac.getParam()
		
		return result;
	}

}
