package com.lfgj.article.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.lfgj.article.model.Article;

/**
 * Generated by Blade.
 * 2017-09-03 11:17:20
 */
public interface ArticleService extends IService<Article>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
