package com.lfgj.product.controller;

import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.common.vo.ShiroUser;
import com.rrgy.core.plugins.dao.Blade;
import com.rrgy.core.shiro.ShiroKit;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.lfgj.product.model.Product;
import com.lfgj.product.model.ProductSale;
import com.lfgj.product.service.ProductSaleService;
import com.lfgj.product.util.ProductListCacheUtil;

/**
 * Generated by Blade.
 * 2017-09-09 11:53:17
 */
@Controller
@RequestMapping("/productSale")
public class ProductSaleController extends BaseController {
	private static String CODE = "productSale";
	private static String PREFIX = "dt_product_sale";
	private static String LIST_SOURCE = "productSale.list";
	private static String BASE_PATH = "/productSale/";
	
	@Autowired
	ProductSaleService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "productSale.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "productSale_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		ProductSale productSale = service.findById(id);
		mm.put("model", JsonKit.toJson(productSale));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "productSale_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		ProductSale productSale = service.findById(id);
		mm.put("model", JsonKit.toJson(productSale));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "productSale_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		ProductSale productSale = mapping(PREFIX, ProductSale.class);
		Product product = Blade.create(Product.class).findById(productSale.getProduct_id());
		if(product == null){
			return error("查无该商品!");
		}
		ShiroUser user = ShiroKit.getUser();
		productSale.setCreator(Integer.valueOf(user.getId().toString()));
		productSale.setCreate_time(new Date());
		productSale.setCode(product.getCode());
		productSale.setDiancs(product.getDiancs());
		productSale.setSort(1);
		boolean temp = service.save(productSale);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		ShiroUser user = ShiroKit.getUser();
		ProductSale productSale = mapping(PREFIX, ProductSale.class);
		productSale.setCreate_time(new Date());
		productSale.setCreator(Integer.valueOf(user.getId().toString()));
		boolean temp = service.update(productSale);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
