package com.rrgy.industry.service.impl;

import java.util.Map;

import org.springframework.stereotype.Service;
import com.rrgy.core.base.service.BaseService;
import com.rrgy.core.plugins.dao.Md;
import com.rrgy.core.toolbox.Paras;
import com.rrgy.industry.model.Industry;
import com.rrgy.industry.service.IndustryService;

/**
 * Generated by Blade.
 * 2017-01-04 14:59:34
 */
@Service
public class IndustryServiceImpl extends BaseService<Industry> implements IndustryService{

	@Override
	public boolean updateStatus(String ids, Object status) {
		Paras paras = Paras.create().set("status", status).set("ids", ids.split(","));
		boolean temp = updateBy("status = #{status}", "id in (#{join(ids)})", paras);
		return temp;
	}

	@Override
	@SuppressWarnings("unchecked")
	public Map<String, Object> findOne(Object id) {
		return Md.selectUnique("industry.findOne", Paras.create().set("id", id), Map.class);
	}

}
