package com.rrgy.benefit.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.benefit.model.Benefit;

/**
 * Generated by Blade.
 * 2017-01-04 12:43:23
 */
public interface BenefitService extends IService<Benefit>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
