package com.rrgy.sms.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-01-04 16:31:00
 */
@Table(name = "dt_code")
@SuppressWarnings("serial")
public class Sms extends BaseModel {

	private Integer id; //编号
	private String mobile; //手机号
	private String code; //验证码
	private Date add_time; //创建时间
	private String isuse;//是否使用（0否，1是）
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public Date getAdd_time() {
		return add_time;
	}
	public void setAdd_time(Date add_time) {
		this.add_time = add_time;
	}
	public String getIsuse() {
		return isuse;
	}
	public void setIsuse(String isuse) {
		this.isuse = isuse;
	}
	
}
