package com.lfgj.article.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.lfgj.article.intercept.CategoryIntercept;
import com.lfgj.article.model.Category;
import com.lfgj.article.service.CategoryService;

/**
 * Generated by Blade.
 * 2017-09-02 19:39:13
 */
@Controller
@RequestMapping("/category")
public class CategoryController extends BaseController {
	private static String CODE = "category";
	private static String PREFIX = "dt_article_category";
	private static String LIST_SOURCE = "category.list";
	private static String BASE_PATH = "/category/";
	
	@Autowired
	CategoryService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "category.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "category_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		Category category = service.findById(id);
		mm.put("model", JsonKit.toJson(category));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "category_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		Category category = service.findById(id);
		mm.put("model", JsonKit.toJson(category));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "category_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE,new CategoryIntercept());
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Category category = mapping(PREFIX, Category.class);
		boolean temp = service.save(category);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Category category = mapping(PREFIX, Category.class);
		boolean temp = service.update(category);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
