package com.rrgy.benefit.model;

import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-01-04 12:43:23
 */
@Table(name = "dt_youhuizubie")
@SuppressWarnings("serial")
public class Benefit extends BaseModel {

	private Integer id;
	private BigDecimal dailishangbili; //代理商比例
	private BigDecimal hehuorenchoucheng; //合伙人抽成
	private BigDecimal jilibili; //激励信使的比例
	private BigDecimal zuanshichoucheng;//钻石抽成
	private BigDecimal jinpaichoucheng; //金牌抽成
	private BigDecimal rangli; //让利
	private BigDecimal shangjiabili; //商家比例
	private BigDecimal shengchoucheng; //省抽成
	private BigDecimal shichoucheng; //市抽成
	private BigDecimal suoshuibili; //缩水比例1
	private BigDecimal suoshuibili2; //缩水比例2
	private String title; //优惠名称
	private BigDecimal tixianxianzhi; //提现限制
	private BigDecimal tuijianbili; //推荐比例
	private BigDecimal tuijianchoucheng; //推荐抽成
	private BigDecimal xinshibili; //信使比例
	private BigDecimal yinpaichoucheng; //银牌抽成
	private BigDecimal jijinchoucheng; //基金抽成
	private BigDecimal gongsichoucheng; //公司抽成
	
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public BigDecimal getDailishangbili() {
		return dailishangbili;
	}
	
	public void setDailishangbili(BigDecimal dailishangbili) {
		this.dailishangbili = dailishangbili;
	}
	
	public BigDecimal getHehuorenchoucheng() {
		return hehuorenchoucheng;
	}
	
	public void setHehuorenchoucheng(BigDecimal hehuorenchoucheng) {
		this.hehuorenchoucheng = hehuorenchoucheng;
	}
	
	public BigDecimal getJilibili() {
		return jilibili;
	}
	
	public void setJilibili(BigDecimal jilibili) {
		this.jilibili = jilibili;
	}
	
	public BigDecimal getJinpaichoucheng() {
		return jinpaichoucheng;
	}
	
	public void setJinpaichoucheng(BigDecimal jinpaichoucheng) {
		this.jinpaichoucheng = jinpaichoucheng;
	}
	
	public BigDecimal getRangli() {
		return rangli;
	}
	
	public void setRangli(BigDecimal rangli) {
		this.rangli = rangli;
	}
	
	public BigDecimal getShangjiabili() {
		return shangjiabili;
	}
	
	public void setShangjiabili(BigDecimal shangjiabili) {
		this.shangjiabili = shangjiabili;
	}
	
	public BigDecimal getShengchoucheng() {
		return shengchoucheng;
	}
	
	public void setShengchoucheng(BigDecimal shengchoucheng) {
		this.shengchoucheng = shengchoucheng;
	}
	
	public BigDecimal getShichoucheng() {
		return shichoucheng;
	}
	
	public void setShichoucheng(BigDecimal shichoucheng) {
		this.shichoucheng = shichoucheng;
	}
	
	public BigDecimal getSuoshuibili() {
		return suoshuibili;
	}
	
	public void setSuoshuibili(BigDecimal suoshuibili) {
		this.suoshuibili = suoshuibili;
	}
	
	public BigDecimal getSuoshuibili2() {
		return suoshuibili2;
	}
	
	public void setSuoshuibili2(BigDecimal suoshuibili2) {
		this.suoshuibili2 = suoshuibili2;
	}
	
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public BigDecimal getTixianxianzhi() {
		return tixianxianzhi;
	}
	
	public void setTixianxianzhi(BigDecimal tixianxianzhi) {
		this.tixianxianzhi = tixianxianzhi;
	}
	
	public BigDecimal getTuijianbili() {
		return tuijianbili;
	}
	
	public void setTuijianbili(BigDecimal tuijianbili) {
		this.tuijianbili = tuijianbili;
	}
	
	public BigDecimal getTuijianchoucheng() {
		return tuijianchoucheng;
	}
	
	public void setTuijianchoucheng(BigDecimal tuijianchoucheng) {
		this.tuijianchoucheng = tuijianchoucheng;
	}
	
	public BigDecimal getXinshibili() {
		return xinshibili;
	}
	
	public void setXinshibili(BigDecimal xinshibili) {
		this.xinshibili = xinshibili;
	}
	
	public BigDecimal getYinpaichoucheng() {
		return yinpaichoucheng;
	}
	
	public void setYinpaichoucheng(BigDecimal yinpaichoucheng) {
		this.yinpaichoucheng = yinpaichoucheng;
	}

	public BigDecimal getJijinchoucheng() {
		return jijinchoucheng;
	}

	public void setJijinchoucheng(BigDecimal jijinchoucheng) {
		this.jijinchoucheng = jijinchoucheng;
	}

	public BigDecimal getGongsichoucheng() {
		return gongsichoucheng;
	}

	public void setGongsichoucheng(BigDecimal gongsichoucheng) {
		this.gongsichoucheng = gongsichoucheng;
	}

	public BigDecimal getZuanshichoucheng() {
		return zuanshichoucheng;
	}

	public void setZuanshichoucheng(BigDecimal zuanshichoucheng) {
		this.zuanshichoucheng = zuanshichoucheng;
	}

}
