package com.rrgy.auditconf.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.auditconf.model.AuditLog;

/**
 * Generated by Blade.
 * 2017-01-05 14:05:29
 */
public interface AuditLogService extends IService<AuditLog>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

	/**
	 * 新增审核记录
	 * @param auditLog
	 * @return
	 */
	boolean insert(AuditLog auditLog);

}
