package com.rrgy.auditconf.service;

import java.util.Map;

import com.rrgy.core.base.service.IService;
import com.rrgy.auditconf.model.AuditConf;

/**
 * Generated by Blade.
 * 2017-01-05 14:05:29
 */
public interface AuditConfService extends IService<AuditConf>{
	
	boolean updateStatus(String ids, Object status);
	
	Map<String, Object> findOne(Object id);

}
