package com.rrgy.person.controller;

import java.util.List;

import org.jeecgframework.poi.excel.entity.ExportParams;
import org.jeecgframework.poi.excel.entity.vo.NormalExcelConstants;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.common.vo.ShiroUser;
import com.rrgy.core.annotation.Before;
import com.rrgy.core.plugins.dao.Md;
import com.rrgy.core.shiro.ShiroKit;
import com.rrgy.core.toolbox.Paras;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.person.common.ExcelPersonParams;
import com.rrgy.person.common.PersonView;
import com.rrgy.person.intercept.PersonIntercept;
import com.rrgy.person.intercept.PersonValidator;
import com.rrgy.person.model.Person;
import com.rrgy.person.service.PersonService;

/**
 * 省级合伙人
 * Generated by Blade.
 * 2016-12-29 12:54:00
 */
@Controller
@RequestMapping("/personProvince")
public class PersonProvinceController extends BaseController {
	private static String CODE = "personProvince";
	private static String PREFIX = "dt_users";
	private static String LIST_SOURCE = "person.listProvince";
	private static String BASE_PATH = "/person/";
	
	@Autowired
	PersonService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "personPartner.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "person_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		PersonView.getPersonView(mm,service,id);
		mm.put("code", CODE);
		return BASE_PATH + "person_moreEdit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		PersonView.getPersonView(mm,service,id);
		mm.put("code", CODE);
		return BASE_PATH + "personPartner_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE,new PersonIntercept());
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Person person = mapping(PREFIX, Person.class);
		boolean temp = service.save(person);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@Before(PersonValidator.class)
	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Person person = mapping(PREFIX, Person.class);
		boolean flag = service.checkMobile(person);
		if(flag){
			boolean temp = service.update(person);
			if (temp) {
				return success(UPDATE_SUCCESS_MSG);
			} else {
				return error(UPDATE_FAIL_MSG);
			}
		}else{
			return error("修改失败，手机号码已存在！");
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
	
	/**
	 * 导出合伙人
	 * @param map
	 * @return
	 */
	@RequestMapping("/exportExcel")
	public String exportExcel(ModelMap map){
		String sql = Md.getSql(LIST_SOURCE);
		Paras para = Paras.create();
		sql = ExcelPersonParams.getParamsAndSql(this.getRequest(), sql, para);
		//获取当前登录用户
		ShiroUser u = ShiroKit.getUser();
		String userName = u.getName();
		List<Person> listPerson = service.find(sql, para);
		map.put(NormalExcelConstants.FILE_NAME,"省级合伙人信息");
        map.put(NormalExcelConstants.CLASS,Person.class);
        map.put(NormalExcelConstants.PARAMS,new ExportParams("省级合伙人列表", "导出人:"+userName,
                "省级合伙人信息"));
        map.put(NormalExcelConstants.DATA_LIST,listPerson);
		return NormalExcelConstants.JEECG_EXCEL_VIEW;
	}
}
