package com.rrgy.auditconf.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-01-05 14:05:29
 */
@Table(name = "dt_audit_conf")
@SuppressWarnings("serial")
public class AuditConf extends BaseModel {

	private Integer id; //主键
	private Integer add_user; //创建人
	private String model_type; //功能模块（0订单，1提现管理）
	private Integer user_id; //系统用户id
	private Date add_time; //创建时间
	private Integer audit_level;//审核级别
	
	//扩展属性
	private String user_name;
	private String add_user_name;
	private String audit_level_name;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getAdd_user() {
		return add_user;
	}
	public void setAdd_user(Integer add_user) {
		this.add_user = add_user;
	}
	public String getModel_type() {
		return model_type;
	}
	public void setModel_type(String model_type) {
		this.model_type = model_type;
	}
	public Integer getUser_id() {
		return user_id;
	}
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}
	public Date getAdd_time() {
		return add_time;
	}
	public void setAdd_time(Date add_time) {
		this.add_time = add_time;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public String getAdd_user_name() {
		return add_user_name;
	}
	public void setAdd_user_name(String add_user_name) {
		this.add_user_name = add_user_name;
	}
	public Integer getAudit_level() {
		return audit_level;
	}
	public void setAudit_level(Integer audit_level) {
		this.audit_level = audit_level;
	}
	public String getAudit_level_name() {
		return audit_level_name;
	}
	public void setAudit_level_name(String audit_level_name) {
		this.audit_level_name = audit_level_name;
	}
	

}
