package com.rrgy.auditconf.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-01-06 11:34:55
 */
@Table(name = "dt_audit_log")
@SuppressWarnings("serial")
public class AuditLog extends BaseModel {

	private Integer id; //主键
	private Integer model_id; //关联模块id
	private String model_type; //功能模块（0订单，1提现管理）
	private Integer user_id; //审批人
	private Date add_time; //审批时间
	private Integer audit_status;//审核状态（1通过，2退回）
	private String audit_remark;//审核原因
	private String audit_level;//审核级别
	
	//扩展属性
	private String user_name;//审核人名字
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getModel_id() {
		return model_id;
	}
	public void setModel_id(Integer model_id) {
		this.model_id = model_id;
	}
	public String getModel_type() {
		return model_type;
	}
	public void setModel_type(String model_type) {
		this.model_type = model_type;
	}
	public Integer getUser_id() {
		return user_id;
	}
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}
	public Date getAdd_time() {
		return add_time;
	}
	public void setAdd_time(Date add_time) {
		this.add_time = add_time;
	}
	public Integer getAudit_status() {
		return audit_status;
	}
	public void setAudit_status(Integer audit_status) {
		this.audit_status = audit_status;
	}
	public String getAudit_remark() {
		return audit_remark;
	}
	public void setAudit_remark(String audit_remark) {
		this.audit_remark = audit_remark;
	}
	public String getAudit_level() {
		return audit_level;
	}
	public void setAudit_level(String audit_level) {
		this.audit_level = audit_level;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

}
