package com.lfgj.system.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rrgy.common.base.BaseController;
import com.rrgy.common.vo.ShiroUser;
import com.rrgy.core.shiro.ShiroKit;
import com.rrgy.core.toolbox.Func;
import com.rrgy.core.toolbox.ajax.AjaxResult;
import com.rrgy.core.toolbox.kit.JsonKit;
import com.lfgj.system.model.Top;
import com.lfgj.system.service.TopService;

/**
 * Generated by Blade.
 * 2017-09-04 21:47:01
 */
@Controller
@RequestMapping("/top")
public class TopController extends BaseController {
	private static String CODE = "top";
	private static String PREFIX = "dt_top";
	private static String LIST_SOURCE = "top.list";
	private static String BASE_PATH = "/top/";
	
	@Autowired
	TopService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "top.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "top_add.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		Top top = service.findById(id);
		mm.put("model", JsonKit.toJson(top));
		mm.put("top", top);
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "top_edit.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		Top top = service.findById(id);
		mm.put("model", JsonKit.toJson(top));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "top_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Top top = mapping(PREFIX, Top.class);
		boolean temp = service.save(top);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Top top = mapping(PREFIX, Top.class);
		Top old_top = service.findById(top.getId());
		ShiroUser user = ShiroKit.getUser();
		String uid = user.getId().toString();

		boolean temp = false;
		if(old_top==null){
			top.setCreate_time(new Date());
			top.setLast_update_time(new Date());
			top.setLast_update_user(Integer.valueOf(uid));
			temp = service.save(top);
		}else{
			top.setLast_update_time(new Date());
			top.setLast_update_user(Integer.valueOf(uid));
			 temp = service.update(top);
		}
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
