package com.rrgy.benefit.service.impl;

import java.util.Map;

import org.springframework.stereotype.Service;
import com.rrgy.core.base.service.BaseService;
import com.rrgy.core.plugins.dao.Md;
import com.rrgy.core.toolbox.Paras;
import com.rrgy.benefit.model.Benefit;
import com.rrgy.benefit.service.BenefitService;

/**
 * Generated by Blade.
 * 2017-01-04 12:43:23
 */
@Service
public class BenefitServiceImpl extends BaseService<Benefit> implements BenefitService{

	@Override
	public boolean updateStatus(String ids, Object status) {
		Paras paras = Paras.create().set("status", status).set("ids", ids.split(","));
		boolean temp = updateBy("status = #{status}", "id in (#{join(ids)})", paras);
		return temp;
	}

	@Override
	@SuppressWarnings("unchecked")
	public Map<String, Object> findOne(Object id) {
		return Md.selectUnique("benefit.findOne", Paras.create().set("id", id), Map.class);
	}

}
