package com.rrgy.person.model;

import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

import org.beetl.sql.core.annotatoin.Table;
import org.jeecgframework.poi.excel.annotation.Excel;

import com.rrgy.benefit.model.Benefit;
import com.rrgy.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-12-29 12:54:25
 */
@Table(name = "dt_users")
@SuppressWarnings("serial")
public class Person extends BaseModel {

	private Integer audit_level;//当前审核级别
	@Excel(name="ID号",orderNum="1")
	private Integer id; //自增ID
	private Integer exp; //经验值
	private Integer group_id; //用户组别
	private Integer hangye;
	private Integer heimingdan;
	private Integer isweixin; //是否是微信号，1、是 0、不是
	private BigDecimal point; //用户积分
	private Integer shangjiId; //上级userId
	@Excel(name="用户状态",orderNum="7",replace={"正常_0","待验证_1","待审核_2","锁定_3"})
	private Integer status; //用户状态,0正常,1待验证,2待审核,3锁定
	private Integer wid; //微信用户表主键Id
	private String address; //联系地址
	private BigDecimal amount; //预存款
	private String avatar; //用户头像
	private String bili; //所属优惠组别
	private String chengnuoshu;
	private String city;
	private String dianmian;
	@Excel(name="天使豆的数量",orderNum="6")
	private BigDecimal dou; //天使豆的数量
	@Excel(name="电子邮箱",orderNum="5")
	private String email; //电子邮箱
	private String faren;
	private String fuzeren;
	private String gangwei;
	@Excel(name="手机号码",orderNum="3")
	private String mobile; //手机号码
	@Excel(name="姓名",orderNum="2")
	private String nick_name; //用户昵称信使姓名 商家名称
	private String password; //用户密码
	private String password2; //用户密码
	private String province;
	private String qiyeguimo;
	private String qq; //QQ号码行业类别
	private String reg_ip; //注册IP
	private String safe_answer; //问题答案商家简介
	private String safe_question; //安全问题主营业务
	private String salt; //6位随机字符串,加密用到
	@Excel(name="用户性别",orderNum="4")
	private String sex; //用户性别
	private String shangjilist;
	private String sheng;
	private String shi;
	private String telphone; //联系电话
	private String tuijianren;
	private String user_name; //用户名
	private String wxName;
	private String wxOpenId;
	private BigDecimal xin; //爱心的数量
	private String xzuobiao;
	private String yingyeshijian;
	private String yingyeshijian2;
	private String yuanyin;
	private BigDecimal yushu; //不足500时 余数
	private String yzuobiao;
	private String zhengjianhaoma;
	private String zhengjianleixing;
	private String zhizhao;
	private String zhizhao2;
	private String zhizhaoleixing;
	private Date birthday; //生日
	@Excel(name="注册时间",orderNum="8",exportFormat="yyyy-MM-dd HH:mm:ss")
	private Date reg_time; //注册时间
	private String status_name;
	private String province_name;
	private String city_name;
	private String group_name;
	private String avatarUrl;
	
	private String notGold;
	private String myGold;
	private String shopGold;
	private String myValidGold;
	
	private String pwd;
	
	List<Benefit> bfList;//比例列表
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getExp() {
		return exp;
	}
	
	public void setExp(Integer exp) {
		this.exp = exp;
	}
	
	public Integer getGroup_id() {
		return group_id;
	}
	
	public void setGroup_id(Integer group_id) {
		this.group_id = group_id;
	}
	
	public Integer getHangye() {
		return hangye;
	}
	
	public void setHangye(Integer hangye) {
		this.hangye = hangye;
	}
	
	public Integer getHeimingdan() {
		return heimingdan;
	}
	
	public void setHeimingdan(Integer heimingdan) {
		this.heimingdan = heimingdan;
	}
	
	public Integer getIsweixin() {
		return isweixin;
	}
	
	public void setIsweixin(Integer isweixin) {
		this.isweixin = isweixin;
	}
	
	public BigDecimal getPoint() {
		return point;
	}
	
	public void setPoint(BigDecimal point) {
		this.point = point;
	}
	
	public Integer getShangjiId() {
		return shangjiId;
	}
	
	public void setShangjiId(Integer shangjiId) {
		this.shangjiId = shangjiId;
	}
	
	public Integer getStatus() {
		return status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public Integer getWid() {
		return wid;
	}
	
	public void setWid(Integer wid) {
		this.wid = wid;
	}
	
	public String getAddress() {
		return address;
	}
	
	public void setAddress(String address) {
		this.address = address;
	}
	
	public BigDecimal getAmount() {
		return amount;
	}
	
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	public String getAvatar() {
		return avatar;
	}
	
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
	
	public String getBili() {
		return bili;
	}
	
	public void setBili(String bili) {
		this.bili = bili;
	}
	
	public String getChengnuoshu() {
		return chengnuoshu;
	}
	
	public void setChengnuoshu(String chengnuoshu) {
		this.chengnuoshu = chengnuoshu;
	}
	
	public String getCity() {
		return city;
	}
	
	public void setCity(String city) {
		this.city = city;
	}
	
	public String getDianmian() {
		return dianmian;
	}
	
	public void setDianmian(String dianmian) {
		this.dianmian = dianmian;
	}
	
	public BigDecimal getDou() {
		return dou;
	}
	
	public void setDou(BigDecimal dou) {
		this.dou = dou;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getFaren() {
		return faren;
	}
	
	public void setFaren(String faren) {
		this.faren = faren;
	}
	
	public String getFuzeren() {
		return fuzeren;
	}
	
	public void setFuzeren(String fuzeren) {
		this.fuzeren = fuzeren;
	}
	
	public String getGangwei() {
		return gangwei;
	}
	
	public void setGangwei(String gangwei) {
		this.gangwei = gangwei;
	}
	
	public String getMobile() {
		return mobile;
	}
	
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	public String getNick_name() {
		return nick_name;
	}
	
	public void setNick_name(String nick_name) {
		this.nick_name = nick_name;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getPassword2() {
		return password2;
	}
	
	public void setPassword2(String password2) {
		this.password2 = password2;
	}
	
	public String getProvince() {
		return province;
	}
	
	public void setProvince(String province) {
		this.province = province;
	}
	
	public String getQiyeguimo() {
		return qiyeguimo;
	}
	
	public void setQiyeguimo(String qiyeguimo) {
		this.qiyeguimo = qiyeguimo;
	}
	
	public String getQq() {
		return qq;
	}
	
	public void setQq(String qq) {
		this.qq = qq;
	}
	
	public String getReg_ip() {
		return reg_ip;
	}
	
	public void setReg_ip(String reg_ip) {
		this.reg_ip = reg_ip;
	}
	
	public String getSafe_answer() {
		return safe_answer;
	}
	
	public void setSafe_answer(String safe_answer) {
		this.safe_answer = safe_answer;
	}
	
	public String getSafe_question() {
		return safe_question;
	}
	
	public void setSafe_question(String safe_question) {
		this.safe_question = safe_question;
	}
	
	public String getSalt() {
		return salt;
	}
	
	public void setSalt(String salt) {
		this.salt = salt;
	}
	
	public String getSex() {
		return sex;
	}
	
	public void setSex(String sex) {
		this.sex = sex;
	}
	
	public String getShangjilist() {
		return shangjilist;
	}
	
	public void setShangjilist(String shangjilist) {
		this.shangjilist = shangjilist;
	}
	
	public String getSheng() {
		return sheng;
	}
	
	public void setSheng(String sheng) {
		this.sheng = sheng;
	}
	
	public String getShi() {
		return shi;
	}
	
	public void setShi(String shi) {
		this.shi = shi;
	}
	
	public String getTelphone() {
		return telphone;
	}
	
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}
	
	public String getTuijianren() {
		return tuijianren;
	}
	
	public void setTuijianren(String tuijianren) {
		this.tuijianren = tuijianren;
	}
	
	public String getUser_name() {
		return user_name;
	}
	
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	
	public String getWxName() {
		return wxName;
	}
	
	public void setWxName(String wxName) {
		this.wxName = wxName;
	}
	
	public String getWxOpenId() {
		return wxOpenId;
	}
	
	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId;
	}
	
	public BigDecimal getXin() {
		return xin;
	}
	
	public void setXin(BigDecimal xin) {
		this.xin = xin;
	}
	
	public String getXzuobiao() {
		return xzuobiao;
	}
	
	public void setXzuobiao(String xzuobiao) {
		this.xzuobiao = xzuobiao;
	}
	
	public String getYingyeshijian() {
		return yingyeshijian;
	}
	
	public void setYingyeshijian(String yingyeshijian) {
		this.yingyeshijian = yingyeshijian;
	}
	
	public String getYingyeshijian2() {
		return yingyeshijian2;
	}
	
	public void setYingyeshijian2(String yingyeshijian2) {
		this.yingyeshijian2 = yingyeshijian2;
	}
	
	public String getYuanyin() {
		return yuanyin;
	}
	
	public void setYuanyin(String yuanyin) {
		this.yuanyin = yuanyin;
	}
	
	public BigDecimal getYushu() {
		return yushu;
	}
	
	public void setYushu(BigDecimal yushu) {
		this.yushu = yushu;
	}
	
	public String getYzuobiao() {
		return yzuobiao;
	}
	
	public void setYzuobiao(String yzuobiao) {
		this.yzuobiao = yzuobiao;
	}
	
	public String getZhengjianhaoma() {
		return zhengjianhaoma;
	}
	
	public void setZhengjianhaoma(String zhengjianhaoma) {
		this.zhengjianhaoma = zhengjianhaoma;
	}
	
	public String getZhengjianleixing() {
		return zhengjianleixing;
	}
	
	public void setZhengjianleixing(String zhengjianleixing) {
		this.zhengjianleixing = zhengjianleixing;
	}
	
	public String getZhizhao() {
		return zhizhao;
	}
	
	public void setZhizhao(String zhizhao) {
		this.zhizhao = zhizhao;
	}
	
	public String getZhizhao2() {
		return zhizhao2;
	}
	
	public void setZhizhao2(String zhizhao2) {
		this.zhizhao2 = zhizhao2;
	}
	
	public String getZhizhaoleixing() {
		return zhizhaoleixing;
	}
	
	public void setZhizhaoleixing(String zhizhaoleixing) {
		this.zhizhaoleixing = zhizhaoleixing;
	}
	
	public Date getBirthday() {
		return birthday;
	}
	
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	
	public Date getReg_time() {
		return reg_time;
	}
	
	public void setReg_time(Date reg_time) {
		this.reg_time = reg_time;
	}

	public String getStatus_name() {
		if(status != null){
			if(status==0){
				status_name = "正常";
			}else if(status==2){
				status_name = "待审核";
			}else{
				status_name = "锁定";
			}
		}else{
			status_name = "待审核";
		}
		return status_name;
	}

	public String getProvince_name() {
		return province_name;
	}

	public void setProvince_name(String province_name) {
		this.province_name = province_name;
	}

	public String getCity_name() {
		return city_name;
	}

	public void setCity_name(String city_name) {
		this.city_name = city_name;
	}

	public String getGroup_name() {
		return group_name;
	}

	public void setGroup_name(String group_name) {
		this.group_name = group_name;
	}

	public String getNotGold() {
		return notGold;
	}

	public void setNotGold(String notGold) {
		this.notGold = notGold;
	}

	public String getMyGold() {
		return myGold;
	}

	public void setMyGold(String myGold) {
		this.myGold = myGold;
	}

	public String getShopGold() {
		return shopGold;
	}

	public void setShopGold(String shopGold) {
		this.shopGold = shopGold;
	}

	public String getMyValidGold() {
		return myValidGold;
	}

	public void setMyValidGold(String myValidGold) {
		this.myValidGold = myValidGold;
	}

	public Integer getAudit_level() {
		return audit_level;
	}

	public void setAudit_level(Integer audit_level) {
		this.audit_level = audit_level;
	}

	public String getAvatarUrl() {
		return avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public void setStatus_name(String status_name) {
		this.status_name = status_name;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public List<Benefit> getBfList() {
		return bfList;
	}

	public void setBfList(List<Benefit> bfList) {
		this.bfList = bfList;
	}

}
