package com.lfgj.online.service.impl;

import java.util.Map;

import org.springframework.stereotype.Service;
import com.rrgy.core.base.service.BaseService;
import com.rrgy.core.plugins.dao.Md;
import com.rrgy.core.toolbox.Paras;
import com.lfgj.online.model.OnlineService;
import com.lfgj.online.service.OnlineServiceService;

/**
 * Generated by Blade.
 * 2017-09-15 16:10:50
 */
@Service
public class OnlineServiceServiceImpl extends BaseService<OnlineService> implements OnlineServiceService{

	@Override
	public boolean updateStatus(String ids, Object status) {
		Paras paras = Paras.create().set("status", status).set("ids", ids.split(","));
		boolean temp = updateBy("status = #{status}", "id in (#{join(ids)})", paras);
		return temp;
	}

	@Override
	@SuppressWarnings("unchecked")
	public Map<String, Object> findOne(Object id) {
		return Md.selectUnique("onlineService.findOne", Paras.create().set("id", id), Map.class);
	}

}
